name: asepe_homes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_screenutil: ^5.9.3
  http: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  animated_snack_bar: ^0.4.0
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
